module.exports = {
	multipass: true,
	full: true,
	plugins: [
		'removeDoctype',
		'removeXMLProcInst',
		'removeComments',
		'removeMetadata',
		'removeEditorsNSData',
		'cleanupAttrs',
		'mergeStyles',
		'inlineStyles',
		'minifyStyles',
		'removeUselessDefs',
		'cleanupNumericValues',
		'convertColors',
		'removeUnknownsAndDefaults',
		'removeNonInheritableGroupAttrs',
		'removeUselessStrokeAndFill',
		'removeViewBox',
		'cleanupEnableBackground',
		'removeHiddenElems',
		'removeEmptyText',
		'convertShapeToPath',
		'convertEllipseToCircle',
		'moveElemsAttrsToGroup',
		'moveGroupAttrsToElems',
		'collapseGroups',
		'convertPathData',
		'convertTransform',
		'removeEmptyAttrs',
		'removeEmptyContainers',
		'mergePaths',
		'removeUnusedNS',
		'sortDefsChildren',
		'removeTitle',
		'removeDesc',
		'removeStyleElement',
		'convertStyleToAttrs',
		'removeDimensions',
	],
};
